AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - '/**/*.spec'
Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Rails/Date:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Documentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Layout/AlignParameters:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 8

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Max: 150

Naming/UncommunicativeMethodParamName:
  MinNameLength: 1

Metrics/BlockNesting:
  CountBlocks: false
