sudo: false
language: ruby
env:
  CI: 1
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  #- rbx-19mode
addons:
  code_climate:
    repo_token: 6da7995a8ca918ac0902d60dc0eb49aa6ae2b94730ea0024e15dcc8f73dd3b1c
