sudo: false
language: ruby

cache:
  directories:
    - ~/.ccache

os:
  - linux

env:
  global:
    - CC_TEST_REPORTER_ID=1abcca9cc0cab51bf0ba6c87cf5e0c68ca7830bc4dcba9728579950ab0a0ee1d
  matrix:
    - CI=1 IMAGEMAGICK_VERSION=6.8.9-10

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec
  - bundle exec rubocop -F

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
