sudo: false
language: ruby

os:
  - linux

env:
  - CI=1 IMAGEMAGICK_VERSION=6.8.9-10

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh

addons:
  code_climate:
    repo_token: 1abcca9cc0cab51bf0ba6c87cf5e0c68ca7830bc4dcba9728579950ab0a0ee1d
